use sys;
#1
CREATE TABLE EMPLOYEE(
	EMPID CHAR(4) NOT NULL,
    NAME CHAR(10) NOT NULL);
CREATE TABLE EMPLOYEE_DETAILS(
	EMPID CHAR(4) NOT NULL,
    NAME CHAR(10) NOT NULL, 
    DESIGNATION CHAR(30) NOT NULL, 
    DOB DATE NOT NULL);

INSERT INTO EMPLOYEE (EMPID, NAME)
VALUES 
('e1' ,'Beth'),
('e2','Ben' ),
('e3' ,'Joe'),
('e4', 'Jonas'),
('e5','Sam');
INSERT INTO EMPLOYEE_DETAILS (EMPID, NAME, DESIGNATION, DOB)
VALUES 
('e1' ,'Beth' ,'HOD' ,'1990-09-08'),
('e2','Ben' ,'Manager','1991-06-04'),
('e5' ,'Smith' , 'Asst.Manager' ,'1991-10-18');

#2
SELECT *FROM EMPLOYEE
WHERE EMPID IN (SELECT EMPID FROM EMPLOYEE_DETAILS);

#3
SELECT *FROM EMPLOYEE
WHERE EMPID NOT IN (SELECT EMPID FROM EMPLOYEE_DETAILS);